name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Breaking'
    labels:
      - 'type: breaking'
  - title: 'Features'
    labels:
      - 'type: feature'
  - title: 'Bug Fixes'
    labels:
      - 'type: bug'
  - title: 'Maintenance'
    labels:
      - 'type: maintenance'
  - title: 'Documentation'
    labels:
      - 'type: docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: minor'
  patch:
    labels:
      - 'type: feature'
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
  default: patch
template: |
  ## Changes

  $CHANGES