name: Release Drafter
on:
  pull_request:
    types:
      - opened
      - closed
      - edited
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  update_release_draft:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        env: 
          GITHUB_REF: ${{ github.ref }}
        run: echo $GITHUB_REF
