name: Release Drafter
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types:
      - closed
      - synchronize
    
jobs:
  update_release_draft:
    # if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        env: 
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: echo $GITHUB_BASE_REF
