name: Release Drafter
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types:
      - closed
      - synchronize
  release:
    types:
      - published
    
jobs:
  update_release_draft:
    # if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        env: 
          GITHUB_BASE_REF: ${{ github.event.release.tag_name }}
        run: echo $GITHUB_BASE_REF
  deploy-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test_gen, test_verify, test_unit, test_lint, test_crd]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker login -u=tmaxcloudck -p=${{ secrets.DOCKER_HUB_PASSWORD }}
          REPO=tmaxcloudck/registry-operator
          IMG=${REPO}:${GITHUB_REF#refs/tags/}
          docker build . -t ${IMG}
          docker tag ${IMG} ${REPO}:latest
          docker push ${IMG}
          docker push ${REPO}:latest

